module.exports = {
    categories: {
        Technology: [
            "AI",
            "Blockchain",
            "Machine Learning",
            "Cybersecurity",
            "Robotics",
            "IoT",
            "Big Data",
            "Cloud Computing",
            "VR",
            "AR",
            "Quantum Computing",
            "SaaS",
            "Data Science",
            "FinTech",
            "Mobile Apps",
            "Web Development",
            "Drones",
            "Automation",
            "Digital Transformation",
            "Smart Cities",
            "APIs",
            "Software Development",
            "Renewable Tech",
            "Startup Tech",
            "Tech Gadgets",
        ],
        "Art & Design": [
            "Painting",
            "Sculpture",
            "Animation",
            "Illustration",
            "Photography",
            "Graphic Design",
            "Typography",
            "Architecture",
            "Contemporary Art",
            "Fashion Design",
            "Interior Design",
            "Calligraphy",
            "Product Design",
            "3D Modeling",
            "Sketching",
            "Mixed Media",
            "Digital Art",
            "Printmaking",
            "Art Exhibitions",
            "Industrial Design",
        ],
        "Film & Video": [
            "Short Films",
            "Documentaries",
            "Cinematography",
            "Screenwriting",
            "Directing",
            "Editing",
            "VFX",
            "Animation Films",
            "Indie Movies",
            "Production",
            "Sound Design",
            "Post-Production",
            "Storyboarding",
            "Casting",
            "Film Festivals",
            "Acting",
            "Film Sets",
            "Film Distribution",
        ],
        Music: [
            "Instrumentals",
            "Vocal Music",
            "Songwriting",
            "Music Production",
            "Recording",
            "Sound Mixing",
            "Band Projects",
            "Classical Music",
            "Music Festivals",
            "Jazz",
            "Rock",
            "Pop",
            "Folk",
            "EDM",
            "Music Videos",
            "Acoustic",
            "Album Releases",
            "Streaming",
        ],
        "Cooking & Food": [
            "Baking",
            "Recipes",
            "Organic Food",
            "Gourmet",
            "Food Photography",
            "Cooking Classes",
            "International Cuisine",
            "Food Trucks",
            "Vegan Recipes",
            "Desserts",
        ],
        "Writing & Publishing": [
            "Novels",
            "Poetry",
            "Blogging",
            "Journalism",
            "Editing",
            "Screenplays",
            "Children's Books",
            "Fiction",
            "Memoirs",
            "Zines",
            "E-books",
            "Creative Writing",
            "Biographies",
            "Essays",
            "Publishing",
        ],
        Gaming: [
            "Video Games",
            "Mobile Games",
            "Game Development",
            "Game Design",
            "Indie Games",
            "Board Games",
            "RPGs",
            "VR Gaming",
            "AR Gaming",
            "Esports",
            "Multiplayer Games",
            "Unity",
            "Unreal Engine",
            "Game Music",
            "Game Storylines",
        ],
        "Health & Wellness": [
            "Yoga",
            "Meditation",
            "Fitness",
            "Dieting",
            "Mental Health",
            "Home Workouts",
            "Supplements",
            "Alternative Medicine",
            "Physiotherapy",
            "Well-being Apps",
            "Personal Training",
            "Outdoor Activities",
        ],
        Education: [
            "E-learning",
            "Online Courses",
            "Tutoring",
            "STEM",
            "Homeschooling",
            "EdTech",
            "Workshops",
            "Training Programs",
            "Classroom Tools",
            "Curriculum Development",
        ],
        "Social Impact": [
            "Nonprofits",
            "Community Projects",
            "Environmental Projects",
            "Volunteering",
            "Activism",
            "Philanthropy",
            "Fundraising",
        ],
    },
};
